### PR TITLE
Update to show nya.is was closed by the owner

### PR DESCRIPTION
**Pull request by elaine-jackson**
See: https://lewd.sx/p/71985 for information on the closure.

### CODE REVIEW

**Comment by tsdko** [comment]
Please don't make entries inconsistent. Example of an entry for a dead site with source code: 9a70eb120e32d1bc790b79a3159722d55d08ecf8

**Comment by thehonkinggoose** [comment]
Like that?

**Comment by tsdko** [comment]
Almost there, now you just need to move the entry below other source-only entries.

**Comment by tsdko** [comment]
Merged.

**Pull request closed without merging**
